"""Central localization registry for every GUI V2 visible string."""

from __future__ import annotations


STRINGS = {
    "app_title": {"zh": "SOCIALSIM 分析与财务工作台 V2", "en": "SOCIALSIM Analysis & Accounting Workbench V2"},
    "language_zh": {"zh": "中文", "en": "中文"},
    "language_en": {"zh": "English", "en": "English"},
    "read_only": {"zh": "只读 · Step15 权威持久化数据", "en": "READ-ONLY · authoritative Step 15 persisted data"},
    "canonical_run": {"zh": "权威运行", "en": "Canonical run"},
    "week_start": {"zh": "起始周", "en": "Start week"},
    "week_end": {"zh": "结束周", "en": "End week"},
    "sector": {"zh": "行业", "en": "Sector"},
    "firm": {"zh": "企业", "en": "Firm"},
    "event_type": {"zh": "事件类型", "en": "Event type"},
    "all": {"zh": "全部", "en": "All"},
    "refresh": {"zh": "刷新", "en": "Refresh"},
    "export": {"zh": "导出当前表", "en": "Export current table"},
    "export_csv_filter": {"zh": "CSV 文件 (*.csv)", "en": "CSV files (*.csv)"},
    "current_week": {"zh": "当前周", "en": "Current week"},
    "status_pass": {"zh": "通过", "en": "PASS"},
    "status_warning": {"zh": "警告", "en": "WARNING"},
    "status_fail": {"zh": "失败", "en": "FAIL"},
    "page_overview": {"zh": "总览", "en": "Overview"},
    "page_population": {"zh": "人口与社会", "en": "Population & Social"},
    "page_household": {"zh": "家庭与结算账户", "en": "Households & Settlement Accounts"},
    "page_labor": {"zh": "劳动力", "en": "Labor"},
    "page_macro": {"zh": "宏观经济", "en": "Macro Economy"},
    "page_sector": {"zh": "行业", "en": "Sectors"},
    "page_firm": {"zh": "企业", "en": "Firms"},
    "page_accounting": {"zh": "财务与查账", "en": "Accounting Department"},
    "page_capital": {"zh": "资本与投资", "en": "Capital & Investment"},
    "page_contract": {"zh": "合同与交易", "en": "Contracts & Transactions"},
    "page_reconciliation": {"zh": "守恒与核对", "en": "Conservation & Reconciliation"},
    "page_reports": {"zh": "报告与导出", "en": "Reports & Export"},
    "subtitle_overview": {"zh": "当前状态、关键趋势与核对结果", "en": "Current state, essential trends, and reconciliation"},
    "subtitle_population": {"zh": "权威人口历史、年龄组与社会事件", "en": "Authoritative demographic history, age groups, and social events"},
    "subtitle_household": {"zh": "社会家庭与经济结算账户严格分离", "en": "Social households separated from economic settlement accounts"},
    "subtitle_labor": {"zh": "就业、未分配劳动力与行业配置", "en": "Employment, unassigned labor, and sector allocation"},
    "subtitle_macro": {"zh": "流量与存量分面展示", "en": "Flows and stocks shown in separate views"},
    "subtitle_sector": {"zh": "按行业观察就业、产出与财务状态", "en": "Employment, output, and finance by sector"},
    "subtitle_firm": {"zh": "逐企业权威经营与财务指标", "en": "Authoritative operating and financial metrics by Firm"},
    "subtitle_accounting": {"zh": "钱在哪里、从哪里来、去了哪里", "en": "Where money is, where it came from, and where it went"},
    "subtitle_capital": {"zh": "投资流量、资本存量与逐资产生命周期", "en": "Investment flows, capital stocks, and asset lifecycle"},
    "subtitle_contract": {"zh": "订单、预付款、交付与资产创建链", "en": "Orders, advances, deliveries, and asset creation"},
    "subtitle_reconciliation": {"zh": "按已定义容差评估，不将制度边界误报为失败", "en": "Tolerance-based checks without treating institutional limits as failures"},
    "subtitle_reports": {"zh": "指标定义、数据可用性与制度边界", "en": "Metric definitions, data availability, and institutional boundaries"},
    "chart_household_flows": {"zh": "家庭周度流量", "en": "Weekly Household Flows"},
    "chart_cash_stocks": {"zh": "现金存量", "en": "Cash Stocks"},
    "chart_population_level": {"zh": "人口总量", "en": "Population Level"},
    "chart_age_groups": {"zh": "历史年龄组结构", "en": "Historical Age-group Structure"},
    "chart_social_accounts": {"zh": "社会家庭与结算账户", "en": "Social Households and Settlement Accounts"},
    "chart_labor_levels": {"zh": "劳动力状态", "en": "Labor Status"},
    "chart_sector_employment": {"zh": "行业就业", "en": "Sector Employment"},
    "chart_macro_flows": {"zh": "收入、消费与储蓄流量", "en": "Income, Consumption, and Saving Flows"},
    "chart_macro_stocks": {"zh": "货币与现金存量", "en": "Money and Cash Stocks"},
    "chart_firm_operations": {"zh": "企业经营流量", "en": "Firm Operating Flows"},
    "chart_firm_balance": {"zh": "企业财务存量", "en": "Firm Financial Stocks"},
    "chart_cash_bridge": {"zh": "现金桥", "en": "Cash Bridge"},
    "chart_balance_sheet": {"zh": "资产负债表", "en": "Balance Sheet"},
    "chart_investment_flows": {"zh": "投资流量", "en": "Investment Flows"},
    "chart_capital_stocks": {"zh": "资本存量", "en": "Capital Stocks"},
    "chart_reconciliation": {"zh": "核对差额", "en": "Reconciliation Gaps"},
    "table_assets": {"zh": "资本资产台账", "en": "Capital Asset Ledger"},
    "table_contracts": {"zh": "权威投资合同链", "en": "Authoritative Investment Chain"},
    "table_balance_sheet": {"zh": "资产负债表明细", "en": "Balance Sheet Detail"},
    "table_availability": {"zh": "数据可用性", "en": "Data Availability"},
    "table_demographic_events": {"zh": "人口事件", "en": "Demographic Events"},
    "section_current_snapshot": {"zh": "当前快照", "en": "Current Snapshot"},
    "section_levels": {"zh": "水平与结构", "en": "Levels and Structure"},
    "section_flows": {"zh": "周度流量", "en": "Weekly Flows"},
    "section_stocks": {"zh": "期末存量", "en": "End-of-period Stocks"},
    "section_firm_snapshot": {"zh": "所选企业快照", "en": "Selected Firm Snapshot"},
    "section_bridge": {"zh": "会计桥", "en": "Accounting Bridges"},
    "section_events": {"zh": "事件记录", "en": "Event Records"},
    "section_registry": {"zh": "中央指标注册表", "en": "Central Metric Registry"},
    "section_boundary": {"zh": "已知制度边界", "en": "Known Institutional Boundary"},
    "section_reconciliation_status": {"zh": "核对状态", "en": "Reconciliation Status"},
    "notice_no_transaction_id": {"zh": "该运行未持久化通用交易 ID；仅显示可权威追踪的订单、买方、供应方与资产来源。", "en": "This run does not persist generic transaction IDs; only authoritative order, buyer, supplier, and asset provenance is shown."},
    "notice_aggregate_flow": {"zh": "无逐交易对手方来源的记录显示为聚合资金流。", "en": "Records without transaction-level counterpart provenance are shown as aggregate cash flows."},
    "notice_age_groups": {"zh": "历史年龄结构来自持久化年龄组，不从最终 Person 快照反推。", "en": "Historical age structure uses persisted age groups and is never reconstructed from the final Person snapshot."},
    "notice_household_scope": {"zh": "社会家庭用于人口分析；结算账户用于工资、消费与现金结算。", "en": "Social households serve demographic analysis; settlement accounts serve wage, consumption, and cash settlement."},
    "notice_boundary_title": {"zh": "下一制度边界", "en": "Next Institutional Boundary"},
    "notice_boundary": {"zh": "持续家庭净储蓄与 LegacyOwner 累积形成企业部门现金流出。Step15 尚未实现政府财政闭合；这不是会计失败。", "en": "Persistent Household net saving and LegacyOwner accumulation drain Firm-sector cash. Government fiscal closure is not implemented in Step 15; this is not an accounting failure."},
    "availability_persisted": {"zh": "本运行已权威持久化", "en": "Authoritative and persisted in this run"},
    "availability_derivable": {"zh": "可由权威持久化数据推导", "en": "Derivable from authoritative persisted data"},
    "availability_runtime": {"zh": "仅运行时存在，历史未保存", "en": "Runtime-only; historical values were not persisted"},
    "availability_not_available": {"zh": "当前模型或本运行未定义/未持久化", "en": "Not defined or persisted by the current model/run"},
    "no_data": {"zh": "当前筛选范围没有可用数据", "en": "No data for the current filters"},
    "rows": {"zh": "行", "en": "rows"},
    "source": {"zh": "来源", "en": "Source"},
    "definition": {"zh": "定义", "en": "Definition"},
    "localized_definition": {"zh": "定义", "en": "Definition"},
    "unit": {"zh": "单位", "en": "Unit"},
    "availability": {"zh": "可用性", "en": "Availability"},
    "metric": {"zh": "指标", "en": "Metric"},
    "value": {"zh": "数值", "en": "Value"},
    "component": {"zh": "项目", "en": "Component"},
    "opening_cash": {"zh": "期初现金", "en": "Opening Cash"},
    "cash_inflows": {"zh": "现金流入", "en": "Cash Inflows"},
    "cash_outflows": {"zh": "现金流出", "en": "Cash Outflows"},
    "closing_cash": {"zh": "期末现金", "en": "Closing Cash"},
    "assets": {"zh": "资产", "en": "Assets"},
    "liabilities": {"zh": "负债", "en": "Liabilities"},
    "equity": {"zh": "账面权益", "en": "Book Equity"},
    "food": {"zh": "食品", "en": "Food"},
    "capital_goods": {"zh": "资本品", "en": "Capital Goods"},
}

STRINGS.update({
    "tab_private_support": {"zh": "家庭支持与流动性", "en": "Private Support & Liquidity"},
    "section_private_support": {"zh": "私域家庭支持：现金流与流动性", "en": "Private Family Support: Cash Flow & Liquidity"},
    "chart_private_support_liquidity": {"zh": "控制组 / 支持组：近零现金与老年家庭流动性", "en": "Control / Support: Near-zero Cash and Elderly Liquidity"},
    "chart_private_support_food": {"zh": "食品销售与企业现金", "en": "Food Sales and Firm Cash"},
    "notice_private_support_unavailable": {"zh": "当前 canonical 数据集未选择成熟谱系家庭支持实验；该区块仅在显式选择实验目录时显示。", "en": "The canonical dataset is unchanged. Select the mature private-support experiment explicitly to open this panel."},
    "notice_private_support_read_only": {"zh": "只读展示已接受的成熟人口谱系家庭支持实验；不重新运行模拟，也不改变 canonical 数据。", "en": "Read-only view of the accepted mature-genealogy private-support experiment; no simulation is rerun and canonical data is unchanged."},
    "label_control": {"zh": "控制：支持关闭", "en": "Control: support off"},
    "label_treatment": {"zh": "处理：支持开启", "en": "Treatment: support on"},
    "label_full_window": {"zh": "全 520 周均值", "en": "Full 520-week mean"},
    "label_last_window": {"zh": "最后 52 周均值", "en": "Last 52-week mean"},
    "label_support_events": {"zh": "支持事件", "en": "Support events"},
    "label_support_value": {"zh": "支持总额", "en": "Total support value"},
    "label_support_payers": {"zh": "付款家庭", "en": "Payer Households"},
    "label_support_recipients": {"zh": "收款家庭", "en": "Recipient Households"},
    "label_child_payer_burden": {"zh": "子女付款后近零占比", "en": "Child payer below-threshold share"},
    "label_food_sales": {"zh": "食品销售", "en": "Food sales"},
    "label_firm_cash": {"zh": "企业现金合计", "en": "Aggregate Firm cash"},
    "label_support_status": {"zh": "数据集", "en": "Dataset"},
    "value_support_active": {"zh": "成熟谱系支持实验（显式选择）", "en": "Mature-genealogy support experiment (explicit)"},
})

STRINGS.update({
    "page_diagnostics": {"zh": "模型诊断", "en": "Model Diagnostics"},
    "subtitle_diagnostics": {"zh": "人口、家庭、劳动、企业、资本与核对的统计检查", "en": "Statistical inspection of demography, households, labor, Firms, capital, and reconciliation"},
    "tab_overview": {"zh": "概览", "en": "Overview"},
    "tab_household_liquidity": {"zh": "家庭现金与流动性分布", "en": "Household Liquidity Distribution"},
    "tab_population_pyramid": {"zh": "人口金字塔", "en": "Population Pyramid"},
    "tab_age_structure": {"zh": "年龄结构", "en": "Age Structure"},
    "tab_income_inequality": {"zh": "收入与不平等", "en": "Income & Inequality"},
    "tab_cash_assets_distribution": {"zh": "现金/资产分布", "en": "Cash / Asset Distribution"},
    "tab_saving_distribution": {"zh": "储蓄", "en": "Saving"},
    "tab_single_firm": {"zh": "单企业", "en": "Single Firm"},
    "tab_cross_firm": {"zh": "横向比较", "en": "Cross-firm Comparison"},
    "tab_market_structure": {"zh": "市场结构", "en": "Market Structure"},
    "tab_capital_pipeline": {"zh": "投资链", "en": "Pipeline"},
    "tab_asset_cohorts": {"zh": "资产批次", "en": "Asset Cohorts"},
    "section_demographic_ratios": {"zh": "人口结构比率", "en": "Demographic Structure Ratios"},
    "section_population_pyramid": {"zh": "所选周人口结构", "en": "Selected-week Population Structure"},
    "section_household_distribution_scope": {"zh": "家庭分布数据边界", "en": "Household Distribution Data Boundary"},
    "section_ranked_snapshot": {"zh": "所选周企业排名", "en": "Selected-week Firm Ranking"},
    "section_firm_health": {"zh": "企业健康与异质性", "en": "Firm Health & Heterogeneity"},
    "section_dispersion": {"zh": "同业离散度", "en": "Within-sector Dispersion"},
    "section_market_concentration": {"zh": "市场集中度", "en": "Market Concentration"},
    "section_labor_quality": {"zh": "劳动市场质量", "en": "Labor-market Quality"},
    "section_sector_cash": {"zh": "部门现金分布", "en": "Sectoral Cash Distribution"},
    "section_capital_pipeline": {"zh": "资本形成 Pipeline", "en": "Capital-formation Pipeline"},
    "section_delivery_lag": {"zh": "订单至首次交付时滞", "en": "Order-to-first-delivery Lag"},
    "section_asset_cohorts": {"zh": "资本资产取得批次", "en": "Capital Asset Acquisition Cohorts"},
    "section_model_diagnostics": {"zh": "统计与经济状态", "en": "Statistical & Economic State"},
    "section_statistical_registry": {"zh": "统计定义注册表", "en": "Statistical Definitions Registry"},
    "chart_population_pyramid": {"zh": "人口金字塔（权威四年龄组）", "en": "Population Pyramid (Authoritative Four Age Groups)"},
    "chart_population_pyramid_week": {"zh": "人口金字塔（第 {week} 周，权威四年龄组）", "en": "Population Pyramid (Week {week}, Authoritative Four Age Groups)"},
    "chart_demographic_ratios": {"zh": "年龄占比与抚养比", "en": "Age Shares & Dependency Ratios"},
    "chart_labor_quality": {"zh": "劳动资格、就业与未分配率", "en": "Eligibility, Employment & Unassigned Rates"},
    "chart_firm_market_share": {"zh": "食品企业已实现销量份额", "en": "Food-firm Realized-sales Shares"},
    "chart_firm_indexed_sales": {"zh": "企业销量指数（区间首个非零值=100）", "en": "Firm Sales Index (First Non-zero in Window = 100)"},
    "chart_ranked_sales": {"zh": "所选周企业销量排名", "en": "Selected-week Firm Sales Ranking"},
    "chart_market_concentration": {"zh": "销量 HHI 与最大企业份额", "en": "Sales HHI & Largest-firm Share"},
    "chart_sector_cash_stocks": {"zh": "部门现金存量", "en": "Sectoral Cash Stocks"},
    "chart_sector_cash_changes": {"zh": "部门现金周变化", "en": "Weekly Sectoral Cash Changes"},
    "chart_capital_pipeline": {"zh": "投资链事件与实物量", "en": "Investment Pipeline Events & Physical Units"},
    "chart_pipeline_event_counts": {"zh": "各 Pipeline 阶段事件数", "en": "Event Counts by Pipeline Stage"},
    "chart_pipeline_physical_units": {"zh": "各 Pipeline 阶段实物量", "en": "Physical Units by Pipeline Stage"},
    "chart_delivery_lag": {"zh": "可关联订单交付时滞分布", "en": "Linked Order-delivery Lag Distribution"},
    "chart_asset_cohorts": {"zh": "按取得年份的资产批次", "en": "Assets by Acquisition-year Cohort"},
    "chart_cohort_cost": {"zh": "批次取得成本与累计折旧", "en": "Cohort Acquisition Cost & Accumulated Depreciation"},
    "chart_model_demography": {"zh": "人口结构诊断", "en": "Demographic Diagnostics"},
    "chart_model_labor": {"zh": "劳动市场诊断", "en": "Labor-market Diagnostics"},
    "chart_model_firms": {"zh": "食品业集中度诊断", "en": "Food-sector Concentration Diagnostics"},
    "chart_model_capital": {"zh": "资本形成诊断", "en": "Capital-formation Diagnostics"},
    "notice_population_resolution": {"zh": "canonical 历史仅权威持久化 0-19、20-39、40-64、65+ 四个年龄组。所选结束周控制本图；未用最终 Person 快照重建历史。", "en": "Canonical history authoritatively persists only four age groups: 0-19, 20-39, 40-64, and 65+. The selected end week controls this view; no history is reconstructed from a final Person snapshot."},
    "notice_population_no_sex": {"zh": "历史人口面板没有完整的年龄×性别横截面，因此使用单侧年龄结构，不虚构男性/女性镜像。", "en": "The historical panel has no complete age-by-sex cross-section, so this is a one-sided age structure rather than an invented male/female mirror."},
    "notice_income_micro_unavailable": {"zh": "本 canonical run 未持久化逐社会家庭收入横截面。均值、分位数、Gini、Lorenz、Top 10%、Bottom 50% 与 P90/P10 均不能由聚合收入或聚合中位数重建。", "en": "This canonical run did not persist a social-household income cross-section. Mean, quantiles, Gini, Lorenz, Top 10%, Bottom 50%, and P90/P10 cannot be reconstructed from aggregate income or aggregate medians."},
    "notice_cash_micro_unavailable": {"zh": "本 canonical run 只有聚合家庭现金存量，没有逐社会家庭现金或可权威估值的权益横截面。因此不生成现金 Gini、Lorenz 或所谓“总财富”分布。", "en": "This canonical run has aggregate Household cash only, with no social-household cash or authoritatively valued equity cross-section. No cash Gini, Lorenz, or mislabeled total-wealth distribution is generated."},
    "notice_saving_micro_unavailable": {"zh": "本 canonical run 未持久化逐社会家庭收入与消费配对记录，不能把聚合储蓄分摊成家庭储蓄额或储蓄率分布。", "en": "This canonical run did not persist paired income and consumption by social Household, so aggregate saving cannot be allocated into Household saving or saving-rate distributions."},
    "notice_household_population_scope": {"zh": "不平等分析总体固定为社会家庭；settlement-only 账户不会被静默混入家庭规模或分布统计。", "en": "The inequality population is explicitly social Households; settlement-only accounts are never silently mixed into family-size or distribution statistics."},
    "notice_market_share_denominator": {"zh": "市场份额定义为企业已实现销量除以同周、同一行业全部企业已实现销量；不跨食品与资本品行业合并分母。", "en": "Market share is Firm realized sales divided by total realized sales in the same sector and week; Food and capital-goods denominators are never combined."},
    "notice_single_supplier": {"zh": "当前资本品行业只有一家供应商，标记为单供应商行业，不展示无信息量的 100% 份额图。", "en": "The current capital-goods sector has one supplier and is labelled a single-supplier sector instead of showing an uninformative 100% share chart."},
    "notice_firm_service_unavailable": {"zh": "逐企业活跃资本服务历史未进入 canonical Firm panel；健康表显示权威资本资产数量与账面价值，不伪造企业资本服务。", "en": "Firm-level active-capital-service history is absent from the canonical Firm panel; the health table shows authoritative asset count and book value instead."},
    "notice_labor_transition_limit": {"zh": "working-age → settlement-valid Person 的中间人数及招聘/释放事件未单独持久化；0–19 岁宽组也无法分离运行时可劳动的 18–19 岁，因此精确劳动资格率不可用。图中仅显示可匹配劳动力占总人口、就业率和未分配率，不重建缺失分母。", "en": "The settlement-valid intermediate count and hire/release events were not persisted. The broad 0-19 band also cannot isolate runtime-eligible ages 18-19, so an exact labor-eligibility rate is unavailable. The chart shows labor-eligible share of population, employment rate, and unassigned rate without reconstructing the missing denominator."},
    "notice_pipeline_link_coverage": {"zh": "订单时滞仅使用具有权威 order_id 且可连接订单与首次交付的记录；缺少连接键的交付不会被猜测匹配。", "en": "Order lags use only records with an authoritative order_id linking an order to its first delivery; deliveries without a link key are not guessed."},
    "notice_model_no_targets": {"zh": "模型诊断展示观测值、趋势、核对结果与已知制度边界，不引入任意经济好坏阈值。", "en": "Model diagnostics show observed values, trends, reconciliations, and known institutional boundaries without arbitrary economic good/bad thresholds."},
    "population_share_axis": {"zh": "累计家庭占比", "en": "Cumulative Household Share"},
    "value_share_axis": {"zh": "累计数值占比", "en": "Cumulative Value Share"},
    "label_acquired": {"zh": "取得", "en": "Acquired"},
    "label_active": {"zh": "活跃", "en": "Active"},
    "label_retired": {"zh": "已退役", "en": "Retired"},
    "label_acquisition_cost": {"zh": "取得成本", "en": "Acquisition Cost"},
    "label_accumulated_depreciation": {"zh": "累计折旧", "en": "Accumulated Depreciation"},
    "label_not_supported": {"zh": "不支持", "en": "Not Supported"},
    "label_not_persisted": {"zh": "未持久化", "en": "Not Persisted"},
    "label_snapshot_week": {"zh": "快照周", "en": "Snapshot Week"},
    "label_single_supplier": {"zh": "单供应商行业", "en": "Single-supplier Sector"},
    "label_male": {"zh": "男性", "en": "Male"},
    "label_female": {"zh": "女性", "en": "Female"},
    "label_exact_age": {"zh": "周岁", "en": "Exact Age"},
    "notice_population_exact": {"zh": "图中使用所选快照周的权威单岁年龄与性别计数，未从最终 Person 快照回推历史。", "en": "The chart uses authoritative exact-age by sex counts at the selected snapshot week; history is not reconstructed from final Person state."},
    "notice_household_statistics_ready": {"zh": "分布统计仅包含社会家庭，不含经济结算专用账户。收入、消费和储蓄均为快照周当周流量，现金为期末存量。", "en": "Distribution statistics include social Households only, excluding settlement-only accounts. Income, consumption, and saving are current-week flows; cash is an end-week stock."},
    "notice_labor_events_ready": {"zh": "招聘、释放、劳动资格进入或退出和行业转移来自逐周权威状态变化；事件原因仅在运行时来源明确时记录。", "en": "Hires, releases, eligibility entries/exits, and sector transfers come from authoritative weekly state transitions; reasons are recorded only where runtime provenance exists."},
    "notice_firm_capital_ready": {"zh": "企业资本服务、资产数、原值、累计折旧、取得、退役及扩张或置换投资均来自逐企业周度权威历史。", "en": "Firm capital service, asset counts, gross values, accumulated depreciation, acquisitions, retirements, and expansion/replacement investment come from authoritative Firm-week history."},
    "chart_exact_population_pyramid": {"zh": "第 {week} 周单岁人口金字塔", "en": "Exact-age Population Pyramid, Week {week}"},
    "chart_distribution_histogram": {"zh": "分布直方图", "en": "Distribution Histogram"},
    "chart_distribution_ecdf": {"zh": "经验累积分布", "en": "Empirical CDF"},
    "chart_distribution_lorenz": {"zh": "洛伦兹曲线", "en": "Lorenz Curve"},
    "chart_gini_history": {"zh": "快照日期基尼系数", "en": "Snapshot-date Gini"},
    "chart_labor_events": {"zh": "劳动力事件流", "en": "Labor Event Flows"},
    "chart_firm_capital_service": {"zh": "企业资本服务历史", "en": "Firm Capital-service History"},
    "section_distribution_summary": {"zh": "分布摘要与分位数", "en": "Distribution Summary and Quantiles"},
    "section_labor_events": {"zh": "招聘、释放与资格变化", "en": "Hiring, Release, and Eligibility Transitions"},
    "section_firm_capital_history": {"zh": "企业资本服务比较", "en": "Firm Capital-service Comparison"},
})

FIELD_LABELS = {
    "age_year": {"zh": "周岁", "en": "Exact Age"},
    "sex": {"zh": "性别", "en": "Sex"},
    "population_count": {"zh": "人数", "en": "Population Count"},
    "household_id": {"zh": "社会家庭 ID", "en": "Social Household ID"},
    "current_week_income": {"zh": "当周收入", "en": "Current-week Income"},
    "current_week_consumption": {"zh": "当周消费", "en": "Current-week Consumption"},
    "current_week_saving": {"zh": "当周储蓄", "en": "Current-week Saving"},
    "gini": {"zh": "基尼系数", "en": "Gini"},
    "turnover_rate": {"zh": "周转率", "en": "Turnover Rate"},
    "active_capital_service": {"zh": "活跃资本服务", "en": "Active Capital Service"},
    "global_step": {"zh": "周", "en": "Week"},
    "firm_id": {"zh": "企业 ID", "en": "Firm ID"},
    "sector": {"zh": "行业", "en": "Sector"},
    "component": {"zh": "项目", "en": "Component"},
    "classification": {"zh": "分类", "en": "Classification"},
    "value": {"zh": "数值", "en": "Value"},
    "metric": {"zh": "指标", "en": "Metric"},
    "max_abs": {"zh": "最大绝对值", "en": "Maximum Absolute Value"},
    "tolerance": {"zh": "容差", "en": "Tolerance"},
    "status": {"zh": "状态", "en": "Status"},
    "asset_id": {"zh": "资产 ID", "en": "Asset ID"},
    "owner_firm_id": {"zh": "所有者企业", "en": "Owner Firm"},
    "origin_order_id": {"zh": "来源订单", "en": "Origin Order"},
    "investment_source": {"zh": "投资来源", "en": "Investment Source"},
    "acquisition_week": {"zh": "取得周", "en": "Acquisition Week"},
    "acquisition_cost": {"zh": "取得成本", "en": "Acquisition Cost"},
    "quantity": {"zh": "数量", "en": "Quantity"},
    "active": {"zh": "活跃", "en": "Active"},
    "accumulated_depreciation": {"zh": "累计折旧", "en": "Accumulated Depreciation"},
    "closing_book_value": {"zh": "期末账面价值", "en": "Closing Book Value"},
    "retirement_week": {"zh": "退休周", "en": "Retirement Week"},
    "simulation_week": {"zh": "模拟周", "en": "Simulation Week"},
    "child_id": {"zh": "儿童 ID", "en": "Child ID"},
    "mother_id": {"zh": "母亲 ID", "en": "Mother ID"},
    "father_id": {"zh": "父亲 ID", "en": "Father ID"},
    "person_id": {"zh": "Person ID", "en": "Person ID"},
    "household_id": {"zh": "家庭 ID", "en": "Household ID"},
    "event_type": {"zh": "事件类型", "en": "Event Type"},
    "order_id": {"zh": "订单 ID", "en": "Order ID"},
    "buyer_firm_id": {"zh": "买方企业", "en": "Buyer Firm"},
    "supplier_firm_id": {"zh": "供应方企业", "en": "Supplier Firm"},
    "physical_units": {"zh": "实物单位", "en": "Physical Units"},
    "cash_amount": {"zh": "现金金额", "en": "Cash Amount"},
    "settled_expenditure": {"zh": "结算投资额", "en": "Settled Expenditure"},
    "capital_asset_created": {"zh": "创建资本资产", "en": "Capital Asset Created"},
    "internal_name": {"zh": "内部指标名", "en": "Internal Name"},
    "display_name_zh": {"zh": "中文名称", "en": "Chinese Name"},
    "display_name_en": {"zh": "英文名称", "en": "English Name"},
    "definition": {"zh": "定义", "en": "Definition"},
    "localized_definition": {"zh": "定义", "en": "Definition"},
    "unit": {"zh": "单位", "en": "Unit"},
    "kind": {"zh": "存量/流量/事件", "en": "Stock / Flow / Event"},
    "aggregation_level": {"zh": "聚合层级", "en": "Aggregation Level"},
    "source_dataset": {"zh": "来源数据集", "en": "Source Dataset"},
    "source_field": {"zh": "来源字段", "en": "Source Field"},
    "availability": {"zh": "可用性", "en": "Availability"},
    "visualization_type": {"zh": "可视化类型", "en": "Visualization Type"},
    "definition_en": {"zh": "英文定义", "en": "English Definition"},
    "age_group": {"zh": "年龄组", "en": "Age Group"},
    "count": {"zh": "数量", "en": "Count"},
    "share": {"zh": "份额", "en": "Share"},
    "population": {"zh": "分析总体", "en": "Population"},
    "unit_of_analysis": {"zh": "分析单位", "en": "Unit of Analysis"},
    "weighting": {"zh": "权重", "en": "Weighting"},
    "exclusion_rules": {"zh": "排除规则", "en": "Exclusion Rules"},
    "source_fields": {"zh": "来源字段", "en": "Source Fields"},
    "time_interpretation": {"zh": "时间语义", "en": "Time Interpretation"},
    "formula": {"zh": "公式", "en": "Formula"},
    "market_share": {"zh": "同业销量份额", "en": "Within-sector Sales Share"},
    "sales": {"zh": "销量", "en": "Sales"},
    "revenue": {"zh": "收入", "en": "Revenue"},
    "production": {"zh": "产量", "en": "Production"},
    "employment": {"zh": "就业", "en": "Employment"},
    "inventory": {"zh": "库存", "en": "Inventory"},
    "operating_profit": {"zh": "营业利润", "en": "Operating Profit"},
    "profit_margin": {"zh": "营业利润率", "en": "Operating Profit Margin"},
    "principal": {"zh": "贷款本金", "en": "Loan Principal"},
    "customer_advance_liability": {"zh": "客户预付款负债", "en": "Customer Advance Liability"},
    "prepaid_investment_asset": {"zh": "预付投资资产", "en": "Prepaid Investment Asset"},
    "capital_book_value": {"zh": "资本账面价值", "en": "Capital Book Value"},
    "capital_asset_count": {"zh": "资本资产数", "en": "Capital Asset Count"},
    "mean": {"zh": "均值", "en": "Mean"},
    "median": {"zh": "中位数", "en": "Median"},
    "minimum": {"zh": "最小值", "en": "Minimum"},
    "maximum": {"zh": "最大值", "en": "Maximum"},
    "cv": {"zh": "变异系数", "en": "CV"},
    "sales_hhi": {"zh": "销量 HHI", "en": "Sales HHI"},
    "largest_firm_share": {"zh": "最大企业份额", "en": "Largest-firm Share"},
    "top2_share": {"zh": "前两家份额", "en": "Top-2 Share"},
    "top3_share": {"zh": "前三家份额", "en": "Top-3 Share"},
    "cross_firm_cv": {"zh": "企业横向变异系数", "en": "Cross-firm CV"},
    "firm_count": {"zh": "企业数", "en": "Firm Count"},
    "sector_structure": {"zh": "行业结构", "en": "Sector Structure"},
    "pipeline_stage": {"zh": "Pipeline 阶段", "en": "Pipeline Stage"},
    "event_count": {"zh": "事件数", "en": "Event Count"},
    "delivery_lag_weeks": {"zh": "交付时滞（周）", "en": "Delivery Lag (weeks)"},
    "order_week": {"zh": "订单周", "en": "Order Week"},
    "delivery_week": {"zh": "首次交付周", "en": "First Delivery Week"},
    "acquisition_cohort_year": {"zh": "取得年份批次", "en": "Acquisition-year Cohort"},
    "asset_count": {"zh": "取得资产数", "en": "Acquired Assets"},
    "active_asset_count": {"zh": "当前活跃资产数", "en": "Currently Active Assets"},
    "retirement_count": {"zh": "有权威退役周资产数", "en": "Assets with Authoritative Retirement Week"},
    "acquired_service_capacity": {"zh": "取得服务能力", "en": "Acquired Service Capacity"},
    "observed_value": {"zh": "观测值", "en": "Observed Value"},
    "trend": {"zh": "趋势", "en": "Trend"},
    "status_basis": {"zh": "状态依据", "en": "Status Basis"},
}


VALUE_LABELS = {
    "availability": {
        "AUTHORITATIVE_AND_PERSISTED": {"zh": "权威且已持久化", "en": "Authoritative and Persisted"},
        "DERIVABLE_FROM_PERSISTED_AUTHORITATIVE_DATA": {"zh": "可由权威持久化数据推导", "en": "Derivable from Persisted Authoritative Data"},
        "AUTHORITATIVE_RUNTIME_ONLY": {"zh": "仅权威运行时可用", "en": "Authoritative Runtime Only"},
        "NOT_AVAILABLE": {"zh": "不可用", "en": "Not Available"},
    },
    "sector": {
        "food": {"zh": "食品", "en": "Food"},
        "capital_goods": {"zh": "资本品", "en": "Capital Goods"},
    },
    "event_type": {
        "birth": {"zh": "出生", "en": "Birth"},
        "death": {"zh": "死亡", "en": "Death"},
        "marriage": {"zh": "结婚", "en": "Marriage"},
        "asset_acquired": {"zh": "资产取得", "en": "Asset Acquired"},
        "asset_retired": {"zh": "资产退役", "en": "Asset Retired"},
        "customer_advance_delivery_recognition": {"zh": "客户预付款交付确认", "en": "Customer Advance Delivery Recognition"},
        "customer_advance_received": {"zh": "收到客户预付款", "en": "Customer Advance Received"},
        "investment_order_settled": {"zh": "投资订单结算", "en": "Investment Order Settled"},
    },
    "kind": {
        "stock": {"zh": "存量", "en": "Stock"},
        "flow": {"zh": "流量", "en": "Flow"},
        "event": {"zh": "事件", "en": "Event"},
        "reconciliation": {"zh": "核对指标", "en": "Reconciliation"},
    },
    "visualization_type": {
        "area": {"zh": "面积图", "en": "Area"},
        "bar": {"zh": "柱状图", "en": "Bar"},
        "event": {"zh": "事件表", "en": "Event Table"},
        "line": {"zh": "折线图", "en": "Line"},
        "status": {"zh": "状态", "en": "Status"},
    },
    "investment_source": {
        "EXPANSION": {"zh": "扩张", "en": "Expansion"},
        "REPLACEMENT": {"zh": "重置", "en": "Replacement"},
    },
    "active": {
        "True": {"zh": "是", "en": "Yes"},
        "False": {"zh": "否", "en": "No"},
    },
    "capital_asset_created": {
        "True": {"zh": "是", "en": "Yes"},
        "False": {"zh": "否", "en": "No"},
    },
    "sector_structure": {
        "SINGLE_SUPPLIER_SECTOR": {"zh": "单供应商行业", "en": "Single-supplier Sector"},
        "MULTI_FIRM_SECTOR": {"zh": "多企业行业", "en": "Multi-firm Sector"},
    },
    "pipeline_stage": {
        "investment_order": {"zh": "投资订单", "en": "Investment Order"},
        "customer_advance": {"zh": "客户预付款", "en": "Customer Advance"},
        "delivery": {"zh": "交付确认", "en": "Delivery Recognition"},
        "asset_acquisition": {"zh": "资产取得", "en": "Asset Acquisition"},
        "asset_retirement": {"zh": "资产退役", "en": "Asset Retirement"},
    },
}


def tr(key: str, language: str = "zh", **values) -> str:
    entry = STRINGS.get(key)
    if entry is None:
        raise KeyError(f"Unregistered GUI V2 localization key: {key}")
    text = entry.get(language) or entry.get("en") or key
    return text.format(**values)


def coverage_rows():
    string_rows = [
        {
            "string_key": key,
            "chinese": value.get("zh", ""),
            "english": value.get("en", ""),
            "chinese_present": bool(value.get("zh")),
            "english_present": bool(value.get("en")),
            "coverage": "PASS" if value.get("zh") and value.get("en") else "FAIL",
        }
        for key, value in sorted(STRINGS.items())
    ]
    field_rows = [
        {
            "string_key": f"field.{key}",
            "chinese": value.get("zh", ""),
            "english": value.get("en", ""),
            "chinese_present": bool(value.get("zh")),
            "english_present": bool(value.get("en")),
            "coverage": "PASS" if value.get("zh") and value.get("en") else "FAIL",
        }
        for key, value in sorted(FIELD_LABELS.items())
    ]
    value_rows = [
        {
            "string_key": f"value.{field}.{raw_value}",
            "chinese": value.get("zh", ""),
            "english": value.get("en", ""),
            "chinese_present": bool(value.get("zh")),
            "english_present": bool(value.get("en")),
            "coverage": "PASS" if value.get("zh") and value.get("en") else "FAIL",
        }
        for field, values in sorted(VALUE_LABELS.items())
        for raw_value, value in sorted(values.items())
    ]
    return string_rows + field_rows + value_rows


def field_label(field: str, language: str = "zh") -> str:
    entry = FIELD_LABELS.get(field)
    if entry:
        return entry.get(language) or entry["en"]
    return field


def value_label(field: str, value, language: str = "zh"):
    entry = VALUE_LABELS.get(field, {}).get(str(value))
    if entry:
        return entry.get(language) or entry["en"]
    return value


__all__ = [
    "FIELD_LABELS", "STRINGS", "VALUE_LABELS", "coverage_rows",
    "field_label", "tr", "value_label",
]
