BASE_REPRODUCTIVE_AGE_MIN = 20
BASE_REPRODUCTIVE_AGE_MAX = 40
BASE_BIRTH_RATE = 0.20
MIN_BIRTH_INTERVAL_WEEKS = 52

# Age fertility curve
FERTILITY_PEAK_AGE = 29
FERTILITY_SPREAD = 6
FERTILITY_FLOOR = 0.25

# Economic fertility factor
ECONOMIC_FACTOR_MIN = 0.40
ECONOMIC_FACTOR_MAX = 1.00
FERTILITY_CHILD_COST_MULTIPLIER = 4.0
ECONOMIC_SECURITY_MIDPOINT = 0.50
ECONOMIC_SECURITY_SLOPE = 6.0

# Milder parity parameters
PARITY_FLOOR = 0.20
PARITY_AMPLITUDE = 0.90
PARITY_SLOPE = 1.00
PARITY_MIDPOINT = 2.35
