FIRM_COUNT = 5

WARMUP_STEPS = 1000
COMPETITION_STEPS = 3000
INITIAL_POPULATION = 5000
SEED = 42

# Household choice is a soft preference, not strict cheapest-first buying.
# Larger values make households more price-sensitive.
PRICE_SENSITIVITY = 3.0
LOYALTY_WEIGHT = 0.25

# Firm behavior after the split.
FIRM_PRICE_ADJUSTMENT_RATE = 0.014
FIRM_PRODUCTION_ADJUSTMENT_RATE = 0.008
FIRM_MARKET_SHARE_ALPHA = 0.08
FIRM_PROFIT_ALPHA = 0.08
FIRM_PRICE_INVENTORY_WEIGHT = 0.35
FIRM_PRICE_SHARE_WEIGHT = 0.15
FIRM_PRICE_MARGIN_WEIGHT = 0.25
FIRM_PRICE_COST_ANCHOR_WEIGHT = 0.75
FIRM_PRODUCTION_INVENTORY_WEIGHT = 0.25
FIRM_PRODUCTION_PROFIT_WEIGHT = 0.08
FIRM_TARGET_MARKUP = 1.22
FIRM_COST_ANCHOR_SCALE = 1.0
FIRM_NORMAL_PRICE_FLOOR_FACTOR = 0.98
FIRM_BELOW_COST_INVENTORY_PRICE_WEIGHT = 0.10
FIRM_INVENTORY_GAP_DEADBAND = 0.08
FIRM_MARKET_SHARE_DEADBAND = 0.015
FIRM_MARGIN_GAP_DEADBAND = 0.020
MAX_PRICE_CHANGE_PER_STEP = 0.012
MAX_PRODUCTION_CHANGE_PER_STEP = 0.008
MIN_FIRM_PRICE = 0.35
MAX_FIRM_PRICE = 3.00
MIN_PRODUCTION_SCALE = 0.45
MAX_PRODUCTION_SCALE = 1.65

# Split values are exactly identical. Small later strategy exploration breaks
# perfect symmetry through firm decisions rather than initial endowments.
INITIAL_PRICE_NOISE = 0.0
INITIAL_PRODUCTIVITY_NOISE = 0.0
STRATEGY_EXPLORATION_NOISE = 0.001
STRATEGY_BIAS_SPREAD = 0.020
STRATEGY_ADAPTATION_RATE = 0.0015
STRATEGY_MIN_BIAS = -0.040
STRATEGY_MAX_BIAS = 0.040
STRATEGY_PROFIT_RATE_DEADBAND = 0.002
STRATEGY_CASH_PRESSURE_WEIGHT = 0.10

# Labor moves slowly toward firms with better recent market share and profit.
LABOR_REALLOCATION_RATE = 0.00
PROFIT_LABOR_WEIGHT = 0.35

# Central-bank buffer stock policy copied from the stabilized main model,
# applied at the firm level with a cash gate.
CB_PURCHASE_RATE = 0.008
CB_PURCHASE_PRICE_HAIRCUT = 0.70
CB_EXCESS_INVENTORY_DAYS = -5.0
CB_MAX_NEW_MONEY_ISSUE_PER_STEP = 0.0
CB_TARGET_FIRM_CASH_SHARE = 1.0
CB_FIRM_CASH_BUFFER_SHARE = 0.025
CB_RELEASE_RATE = 0.60
CB_PRICE_ANCHOR = 1.50
CB_POVERTY_SUBSIDY_RATE = 0.015
